remote_theme: pages-themes/hacker@v0.2.0
#theme: minima
#remote_theme: jekyll/minima@d4d779a
title: ðŸ“¡ MQTT Antena
description: A tool to help develop, test & monitor MQTT messages
author: fbossolan
google_analytics: G-BE8RD9ST7H
minima:
  skin: dark

  social_links:
     - title: MQTT Antena repository at GitHub
       icon: github
       url: "https://github.com/fbossolan/mqtt-antena/tree/main"
     - title: MQTT Antena Dockerhub
       icon: docker
       url: "https://hub.docker.com/r/fbossolan/mqtt-antena"
  nav_pages:
     - CHANGELOG.md
  hide_site_feed_link: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
