#remote_theme: pages-themes/hacker@v0.2.0
#theme: minima
remote_theme: jekyll/minima@d4d779a
title: ðŸ“¡ MQTT Antena
description: A tool to help develop & test MQTT messages
author: fbossolan
google_analytics: G-XXXXXXXXXX # Replace with your GA4 Measurement ID
minima:
  skin: dark

  social_links:
     - title: MQTT Antena repository at GitHub
       icon: github
       url: "https://github.com/fbossolan/mqtt-antena/tree/main"
    #  - title: Jekyll at X (formerly Twitter)
    #    icon: x-twitter
    #    url: "https://x.com/jekyllrb"
  nav_pages:
     - about.md
  hide_site_feed_link: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
